ready app for deployment

diff --git a/SearchPolymerFrontEnd/static/bower_components/paper-button/.travis.yml b/SearchPolymerFrontEnd/static/bower_components/paper-button/.travis.yml
--- a/SearchPolymerFrontEnd/static/bower_components/paper-button/.travis.yml
+++ b/SearchPolymerFrontEnd/static/bower_components/paper-button/.travis.yml
@@ -1,22 +1,31 @@
 language: node_js
-sudo: false
+sudo: 'false'
 before_script:
-  - npm install web-component-tester
-  - npm install bower
-  - 'export PATH=$PWD/node_modules/.bin:$PATH'
-  - bower install
+  - npm install -g polymer-cli
+  - polymer install --variants
+  - >-
+    npm run update-types && git diff --exit-code || (echo -e
+    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
+    update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
-    - secure: geFs7Ipj7/9knSKT2FEYAB7b/zbmgWFXCgZm7cEcrG71EX/HB1do3spANGOlRly77xaZtNNF1OGYBHIP36DSyMEHRYj6TYtTrPIr2ySeHvoOv0nzYakXdscxBvfI5HJrNiFpld80KoGl8vKfroLNpVLallgumX3diydypolvW1I=
-    - secure: IILEhg3m49exN5hpxbPP1JA/q+s4v/QpOMbDiXVRV4Uz1XwOPGLCyrAB0ENjwzMCyeOah1Z2MyQSUiPisLheHKvZifhviNqizWN//8EDkg1gkU0R6egGdotD5mBb3UpCD0CNZ8+D0FYwOpdCWCruwr7N+zDUN+6r5H07KP/VeUU=
-node_js: 4
+    - secure: >-
+        UCS5TSfKVWi6c8j/jJZPOX7JvLPxs2GiEua2lZOrgFD2U+SPk3oIToOJ3j/ItMdK2imcrHOtA369sEyYZbrUQVAu+XWX3B2xar5VK8uD12Mw57D1eq1WAQ5qKiDBQ4b0rhuYm2LX7pQhtU8YgUHrXs60GT8YXW0T+NeRieXHRas=
+    - secure: >-
+        dX4A2hHUV0UUtwONe4JjODrq5BFS1d7z8WUZgoXsaPV+t4spnZOSMLCfruKu83MH1qIJltvZArMN0jcXUuiF2/tU0JffuwS1wqjNhp7LVfn0cAOQVx/XgS8+yzgKoHgbSRgb1dGvjPv4VJX5OdzCrH+asfBUegmK9XCvVPw5wOM=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
+  chrome: stable
 script:
-  - xvfb-run wct
-  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
+  - xvfb-run polymer test
+  - >-
+    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
+    fi
+dist: trusty
+cache:
+  directories:
+    - node_modules
